#!/usr/bin/env node

/**
 *
 * @author xgqfrms
 * @license MIT
 * @copyright xgqfrms 2019.05.12
 *
 * @description APP_ENV Genarator
 * @augments
 * @example node env-generator.js env=dev
 *
 */

const packageInfo = require("./package.json");

const fs = require("fs");

const {
  version,
  argv,
  // versions,
  // arch,
  // platform,
  // env,
} = process;

// v12.18.0
console.log('\n🚀 your node.js version =', version.substr(1).split('.')[0]);

// const args = process.argv.slice(2) || [];
const args = argv.slice(2) || [];

const filename = "./env.js";

const isPureNumber = (str = '') => {
  // [...''.padEnd(10, 'x')].map((item, i) => i);
  // (10) [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  // [...''.padEnd(10, 'x')].map((item, i) => `${i}`);
  // (10) ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
  const numberDict = [...''.padEnd(10, 'x')].map((item, i) => `${i}`);
  const arr = `${str}`.split('');
  return arr.every(item => numberDict.includes(item));
  // arr.every(item => {
  //   console.log('item', item, dict, dict.includes(item))
  //   return dict.includes(item);
  // });
}

let key = "";
let env = "";
if (!args[0]) {
  args[0] = "";
  // console.log('ane version =', packageInfo.version);
  // echo `version = ${packageInfo.version}`;
  console.log(`version = ${packageInfo.version}`);
  key = 'APP_ENV';
  env = 'dev';
} else {
  // echo `version = ${packageInfo.version}`;
  // console.log('ane version =', packageInfo, packageInfo.version);
  // env = args[0].substr(4);
  const tempArr = args[0].split('=');
  // key = tempArr[0] ?? 'APP_ENV';
  key = tempArr[0] || 'APP_ENV';
  env = isPureNumber(tempArr[1]) ? parseInt(tempArr[1]) : tempArr[1];
  // console.log('isPureNumber(tempArr[1])', isPureNumber(tempArr[1]), env, typeof env);
}

// env = isPureNumber(env) ? env : `${env}`;
// env = isPureNumber(env) ? env : env.toString();

// console.log('env =', env, typeof env);

let defaultTemplate = ``;
let envTemplate = ``;
if (isPureNumber(env)) {
  defaultTemplate = `// default\nconst ${key} = ${env};\nexport default ${key};\n`;
  envTemplate = `// 🎉\nconst ${key} = ${env};\nexport default ${key};\n`;
} else {
  defaultTemplate = `// default\nconst ${key} = '${env}';\nexport default ${key};\n`;
  envTemplate = `// 🎉\nconst ${key} = '${env}';\nexport default ${key};\n`;
}

// console.log('defaultTemplate =', defaultTemplate);
// console.log('envTemplate =', envTemplate);

// const defaultTemplate = `
// // default
// const ${key} = ${env};
// export default ${key};
// `;

// const envTemplate = `
// // 🎉
// const ${key} = ${env};
// export default ${key};
// `;

fs.open(filename, "r", (err, fd) => {
  if (err) {
    fs.writeFile(filename, defaultTemplate, (err, fd) => {
      if (err) {
        console.log(`writeFile err =`, err);
      }
    });
  } else {
    fs.writeFile(filename, envTemplate, (err, fd) => {
      if (err) {
        console.log(`writeFile err =`, err);
      }
    });
  }
});

